language: node_js
node_js: "stable"

after_success:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  firefox: 53.0
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

install: 
  - npm install
script:
  - npm run test